import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { states } from '@/store'
import { handleConnect, handleDisconnect } from '@/walletconnect'

const connectHTML = <button onClick={handleConnect} >Connect</button>
const disconenctHTML = <button onClick={handleDisconnect} >Disconnect</button>

export default function Home() {

  const address = states.address()
  const chainId = states.chainId()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {address ? disconenctHTML : connectHTML}        
        <span>address: {address}</span>
        <span>chain ID: {chainId}</span>
      </main>
    </>
  )
}
